# Generated by Django 4.1.7 on 2023-03-02 20:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_name', models.CharField(max_length=150)),
                ('english_name', models.CharField(max_length=150)),
                ('national_id', models.CharField(max_length=14, unique=True)),
                ('data_of_birth', models.DateField()),
                ('passport_number', models.CharField(max_length=8, unique=True)),
                ('passport_start', models.DateField()),
                ('passport_end', models.DateField()),
                ('visa_type', models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')], max_length=150)),
                ('visa_number', models.CharField(max_length=150)),
                ('visa_start', models.DateField()),
                ('visa_end', models.DateField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.company')),
            ],
        ),
    ]
