# Generated by Django 4.1.7 on 2023-03-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_passenger_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passenger',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='passenger',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passport_number',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='visa_type',
            field=models.CharField(default='زيارة شخصية', max_length=150),
        ),
    ]
