# Generated by Django 4.1.7 on 2023-03-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_passenger_options_passenger_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='national_id',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passport_number',
            field=models.CharField(max_length=9),
        ),
    ]
